---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: development-services
images:
  - name: image
    newName: 463167595377.dkr.ecr.eu-west-1.amazonaws.com/hello-service:0.0.1
configMapGenerator:
  - name: hello-service-configuration
    behavior: merge
    files:
      - config/application.yml
      - config/log4j2.xml
patchesStrategicMerge:
  - secrets-service-account.yaml
  - ingress-internal.yaml
  - service-monitor.yaml
  - deployment.yaml
  - hpa.yaml
