---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hello-service-secret-aws-provider
spec:
  provider: aws
  secretObjects:
    - secretName: hello-service-secret
      type: Opaque
      data:
        - key: rds-password
          objectName: rdsPassword
  parameters:
    objects: |
      - objectName: hello-db-RDS-service-user-password
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: rdsPassword
