---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: swfs-grafana-agent
  name: hello-service-monitor
  namespace: development-services
spec:
  endpoints:
    - interval: 15s
      port: http-management
      path: /manage/prometheus
  namespaceSelector:
    matchNames:
      - development-services
